name = "rohiniai-tracking"
main = "src/index.js"
compatibility_date = "2026-05-04"

[[d1_databases]]
binding = "DB"
database_name = "rohiniai_clicks"
database_id = "09a55d44-6dc2-4d12-a5ab-b4252aa50791"

[observability]
enabled = true
